package NemUp_Main;

import java.util.Enumeration;
import java.util.Enumeration;
import java.util.Vector;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.beans.*;
import javax.swing.event.*;

/*
 * NemUp_Start.java
 */
/**
 *
 * @author admin
 */
public class NemUp_Start extends javax.swing.JFrame {

    public static DefaultListModel objectModel;

    public NemUp_ObjectFrame of;

    /**
     * Creates new form MainFrame
     */
    public NemUp_Start() {

        initComponents();
        objectModel = new DefaultListModel();
        jListObjects.setModel(objectModel);
        setLocation(240, 120);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu = new javax.swing.JPopupMenu();
        jMenuItemShow = new javax.swing.JMenuItem();
        jMenuItemHide = new javax.swing.JMenuItem();
        jMenuItemRemove = new javax.swing.JMenuItem();
        jToolBar = new javax.swing.JToolBar();
        jBtnLocalMachine = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jBtnAddObject = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jBtnRemoveObject = new javax.swing.JButton();
        jSplitPane = new javax.swing.JSplitPane();
        jScrollPaneObjects = new javax.swing.JScrollPane();
        jListObjects = new javax.swing.JList();
        jScrollPaneRight = new javax.swing.JScrollPane();
        jDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuIPAddress = new javax.swing.JMenu();
        jMenuItemPing = new javax.swing.JMenuItem();
        jMenuItemTrace = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jMenuItemMsg = new javax.swing.JMenuItem();

        jMenuItemShow.setText("Show");
        jMenuItemShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemShowActionPerformed1(evt);
            }
        });
        jPopupMenu.add(jMenuItemShow);

        jMenuItemHide.setText("Hide");
        jMenuItemHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHideActionPerformed(evt);
            }
        });
        jPopupMenu.add(jMenuItemHide);

        jMenuItemRemove.setText("Remove");
        jMenuItemRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRemoveActionPerformed(evt);
            }
        });
        jPopupMenu.add(jMenuItemRemove);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 100, 0, 0));

        jToolBar.setRollover(true);

        jBtnLocalMachine.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jBtnLocalMachine.setText("Physical Machine");
        jBtnLocalMachine.setFocusable(false);
        jBtnLocalMachine.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnLocalMachine.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnLocalMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLocalMachineActionPerformed(evt);
            }
        });
        jToolBar.add(jBtnLocalMachine);
        jToolBar.add(jSeparator1);

        jBtnAddObject.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jBtnAddObject.setText("Add Network IP");
        jBtnAddObject.setFocusable(false);
        jBtnAddObject.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnAddObject.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnAddObject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddObjectActionPerformed(evt);
            }
        });
        jToolBar.add(jBtnAddObject);
        jToolBar.add(jSeparator2);

        jBtnRemoveObject.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jBtnRemoveObject.setText("Remove Network IP");
        jBtnRemoveObject.setFocusable(false);
        jBtnRemoveObject.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnRemoveObject.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnRemoveObject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRemoveObjectActionPerformed(evt);
            }
        });
        jToolBar.add(jBtnRemoveObject);

        jSplitPane.setDividerLocation(150);
        jSplitPane.setDividerSize(8);
        jSplitPane.setOneTouchExpandable(true);

        jScrollPaneObjects.setBorder(javax.swing.BorderFactory.createTitledBorder("Objects"));
        jScrollPaneObjects.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N

        jListObjects.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListObjects.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListObjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListObjectsMouseClicked(evt);
            }
        });
        jListObjects.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jListObjectsKeyPressed(evt);
            }
        });
        jScrollPaneObjects.setViewportView(jListObjects);

        jSplitPane.setLeftComponent(jScrollPaneObjects);

        jScrollPaneRight.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPaneRight.setMinimumSize(new java.awt.Dimension(80, 80));
        jScrollPaneRight.setPreferredSize(new java.awt.Dimension(40, 40));
        jScrollPaneRight.setViewportView(jDesktopPane);

        jSplitPane.setRightComponent(jScrollPaneRight);

        jMenuBar.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N

        jMenuIPAddress.setText("IP Configuration");
        jMenuIPAddress.setEnabled(false);
        jMenuIPAddress.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N

        jMenuItemPing.setText("Ping");
        jMenuItemPing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPingActionPerformed(evt);
            }
        });
        jMenuIPAddress.add(jMenuItemPing);

        jMenuItemTrace.setText("Trace route");
        jMenuItemTrace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTraceActionPerformed(evt);
            }
        });
        jMenuIPAddress.add(jMenuItemTrace);
        jMenuIPAddress.add(jSeparator3);
        jMenuIPAddress.add(jSeparator4);

        jMenuItemMsg.setText("Send Message");
        jMenuItemMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMsgActionPerformed(evt);
            }
        });
        jMenuIPAddress.add(jMenuItemMsg);

        jMenuBar.add(jMenuIPAddress);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE))
                    .addComponent(jToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jBtnAddObjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddObjectActionPerformed
        NetworkIP_Add.main(null);
}//GEN-LAST:event_jBtnAddObjectActionPerformed

    private void jBtnLocalMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLocalMachineActionPerformed
        ShowLocalMachineFrame();
}//GEN-LAST:event_jBtnLocalMachineActionPerformed

    private void jBtnRemoveObjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRemoveObjectActionPerformed
        RemoveObject();
}//GEN-LAST:event_jBtnRemoveObjectActionPerformed

    private void jMenuItemShowActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemShowActionPerformed1
        ShowObjectFrame();
}//GEN-LAST:event_jMenuItemShowActionPerformed1

    private void jMenuItemHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHideActionPerformed
        HideObjectFrame();
    }//GEN-LAST:event_jMenuItemHideActionPerformed

    private void jMenuItemRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRemoveActionPerformed
        RemoveObject();
    }//GEN-LAST:event_jMenuItemRemoveActionPerformed

    private void jMenuItemPingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPingActionPerformed
        of.ExecuteCmd("Ping ", of.getSelectedAdr());
    }//GEN-LAST:event_jMenuItemPingActionPerformed

    private void jMenuItemTraceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTraceActionPerformed
        of.ExecuteCmd("Tracert ", of.getSelectedAdr());
    }//GEN-LAST:event_jMenuItemTraceActionPerformed

    private void jMenuItemMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMsgActionPerformed
        String msg = JOptionPane.showInputDialog(NemUp_Start.this,
                "Type the message you want to send ");
        if (msg == null) {
            return;
        }
        of.ExecuteProcess("net send " + of.getSelectedAdr() + " " + msg);
    }//GEN-LAST:event_jMenuItemMsgActionPerformed

    private void jListObjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListObjectsMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) // Right Mouse Click
        {
            ShowObjectsPopupMenu(evt.getX(), evt.getY());
        }
        if (evt.getClickCount() == 2) // Double Mouse Click
        {
            ShowObjectFrame();
        }
}//GEN-LAST:event_jListObjectsMouseClicked

    private void jListObjectsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jListObjectsKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_DELETE) // Pressing Del buttom
        {
            RemoveObject();
        }
        if (key == KeyEvent.VK_ENTER) // Pressing Enter buttom
        {
            ShowObjectFrame();
        }
}//GEN-LAST:event_jListObjectsKeyPressed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NemUp_Start().setVisible(true);
            }
        });
    }

    public void AddObjectFrame(String title) {
        of = new NemUp_ObjectFrame(title, this);
        of.setTitle(title);
        of.setVisible(true);
        jDesktopPane.add(of);
        try {
            of.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
        }
    }

    public void AddLocalMachineFrame() {
        NemUp_Physical lm = new NemUp_Physical();
        lm.setVisible(true);
        jDesktopPane.add(lm);
        try {
            lm.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
        }
    }

    public void ShowLocalMachineFrame() {
        String object = "Local Machine";
        for (JInternalFrame frame : jDesktopPane.getAllFrames()) {
            if (frame.getTitle().equals(object)) {
                try {
                    frame.setSelected(true);
                } catch (java.beans.PropertyVetoException e) {
                    return;
                }
                return;
            }
        }
        AddLocalMachineFrame();
    }

    public void ShowObjectFrame() {
        String object = getSelectedElement(jListObjects);
        if (!IPAddress.validObject(object)) {
            return;
        }
        for (JInternalFrame frame : jDesktopPane.getAllFrames()) {
            if (frame.getTitle().equals(object)) {
                try {
                    frame.setSelected(true);
                } catch (java.beans.PropertyVetoException e) {
                    return;
                }
                return;
            }
        }
        AddObjectFrame(object);
    }

    public void HideObjectFrame() {
        String object = getSelectedElement(jListObjects);
        for (JInternalFrame frame : jDesktopPane.getAllFrames()) {
            if (frame.getTitle().equals(object)) {
                try {
                    frame.setClosed(true);
                } catch (java.beans.PropertyVetoException e) {
                }
            }
        }
    }

    public void RemoveObject() {
        String object = getSelectedElement(jListObjects);
        if (object == null) {
            return;
        }
        if (!IPAddress.validObject(object)) {
            return;
        }

        int choise = JOptionPane.showConfirmDialog(NemUp_Start.this,
                "Are you sure you want to delete " + object + "?", "Delete Object",
                JOptionPane.OK_CANCEL_OPTION);
        if (choise != JOptionPane.OK_OPTION) {
            return;
        }

        HideObjectFrame();

        objectModel.remove(jListObjects.getSelectedIndex());
        ObjectsList.removeObject(object);
    }

    public static Vector getElements(DefaultListModel model) {
        Enumeration enumeration = model.elements();
        Vector<String> vector = new Vector<String>();
        while (enumeration.hasMoreElements()) {
            vector.add(enumeration.nextElement().toString());
        }
        return vector;
    }

    public static void AddNewElement(JList list, DefaultListModel model, String object) {
        model.addElement(object);
        list.requestFocus();
    }

    public void ShowObjectsPopupMenu(int x, int y) {
        // Get mouse posiiton
        jListObjects.getCellBounds(x, x);

        // Show Popup Menu at the selected item
        String object = getSelectedElement(jListObjects);
        if (!IPAddress.validObject(object)) {
            return;
        }
        jPopupMenu.show(jListObjects, x, y);
    }

    public static String getSelectedElement(JList list) {
        try {
            return list.getSelectedValue().toString();
        } catch (Exception e) {
            return "";
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAddObject;
    private javax.swing.JButton jBtnLocalMachine;
    private javax.swing.JButton jBtnRemoveObject;
    private javax.swing.JDesktopPane jDesktopPane;
    public static javax.swing.JList jListObjects;
    private javax.swing.JMenuBar jMenuBar;
    public javax.swing.JMenu jMenuIPAddress;
    private javax.swing.JMenuItem jMenuItemHide;
    private javax.swing.JMenuItem jMenuItemMsg;
    private javax.swing.JMenuItem jMenuItemPing;
    private javax.swing.JMenuItem jMenuItemRemove;
    private javax.swing.JMenuItem jMenuItemShow;
    private javax.swing.JMenuItem jMenuItemTrace;
    private javax.swing.JPopupMenu jPopupMenu;
    private javax.swing.JScrollPane jScrollPaneObjects;
    private javax.swing.JScrollPane jScrollPaneRight;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JToolBar jToolBar;
    // End of variables declaration//GEN-END:variables
}
